# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


## => Language and Timezone
##############################
lang: fr

## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Mélodie KOUY
  url       : ""
  avatar    : assets\images\autoportrait-2025-carre.png
  bio       : >- # this means to ignore newlines until the next "variable"
    Œil curieux et doigts de fée,
    j’aime confronter ma pluridisciplinarité,
    autant dans la programmation que dans l’illustration,
    sur des projets ludiques et symboliques,
    pour vous, pour moi et pour le public qui les explore
    afin d'éveiller, transmettre et faire rêver.
  email     : melodiekouy@gmail.com
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : "melodie-kouy" # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : "Melokye" # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


# title: Melokye
description: >- # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username : melokye.crea
# github_username:  Melokye

# Build settings
# theme: minima
theme: jekyll-text-theme
# plugins:
  # - jekyll-feed
  # - jekyll-last-modified-at

collections_dir: collections
collections:
  skills:
    output: true
  projects:
    output: true
  formations:
  social-media:

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"
  -
    scope:
      path: "collections/_projects/*"
      type: "projects"
    values:
      layout: "project"
      title:
      skills:
      debut:
      fin: 
      team:


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
